### ISSUE TITLE
samd_xtend branch: ports/samd/mpconfigport.h has unresolved merge notes

### ISSUE THREAD

**Issue by ricksorensen** [robert-hh/micropython#12]
Starting at line 74:
```
<<<<<<< HEAD
#define MICROPY_PY_IO                       (1)
=======
#define MICROPY_PY_IO_FILEIO                (1)
>>>>>>> 30d3d6ba2 (samd: Restructure the mpconfigxxx.h files.)
```
I believe the MICROPY_PY_IO_FILEIO line should be removed based on base micropython (1.19 +) comments.

**Comment by robert-hh** [comment]
Thanks. I noticed that yesterday as well, but forgot to push the change. Which is done now.
