### ISSUE TITLE
Looking for assistance to setup w60x build environment

### ISSUE THREAD

**Issue by LexxM3** [robert-hh/micropython#16]
Robert,

I'd like to setup my own build environment for w60x branch.  Getting stuck on the preliminaries.

1. **"WM_SDK version G3.1 or above"**: Is "G3.1 or above" statement equivalent to "G3.01 or above"?  In other words, does G3.04 meet the minimum requirement?  I am able to find G3.04, but I cannot find anything resembling G3.1 or, say, G3.4 formatted version numbers.
2. I am able to complete the mpy_cross build step successfully.
3. So, trying to use WM_SDK_W60X_G3.04 and trying to run `make V=s` in `ports/w60x`, we discover (among other errors to be addressed later) that there is no such path as `find: ‘/opt/tools/WM_SDK_W60X/Src/Wlan’: No such file or directory`.  In fact, the only directories in `W60X/Src` are `App`, `Network`, and `OS`.  Is this because G3.04 is not the right version?  Is so, back to question 1.

Build environment is x86 Debian latest. Any pointers would be appreciated.

**Comment by robert-hh** [comment]
I have modified the WM_SDK a little bit and use the one here: https://github.com/robert-hh/WM_SDK_W60X. It may have been better to just put these files in a backport local directory and leave the SDK untouched. I have as well set `WMSDK_PATH` to the place where the SDK is located. I have nothing in /opt related to the W600 build. My OS is the latest Debian as well.

**Comment by robert-hh** [comment]
I see that you had found already my modified SDK. So it's maybe just the WMSDK_PATH setting. The full setting I have in my ~/.bashrc is: 
`export WMSDK_PATH=/home/robert/Downloads/MicroPython/WM_SDK_W60X_G3.04.00`
There may be a reason why I did not use `$HOME` instead of `/home/robert`.

**Comment by LexxM3** [comment]
Ok, that's helpful, but not there yet.  I am now using a fork of your SDK repo verbatim.  Same initial error:  `find: ‘/work/hub/WM_SDK_W60X/Src/Wlan’: No such file or directory`.  As before, there is no `Wlan` directory in `WM_SDK_W60X/Src/`

Examining the Makefile, TOPDIR gets set to WMSDK_PATH and first interesting access to TOPDIR is `include $(TOPDIR)/Tools/subdir.mk`.  In turn, `subdir.mk` has multiple references to `${TOPDIR}/Src/Wlan/` ... which doesn't exist.

So I think there is some kind of versionitis going on in my setup.

Update: I had a couple of setup problems:
- I installed the Mac version for the cross compiler for some reason, fixed with Linux version
- then, turns out I needed some extra libraries on Debian 64bit to run 32bit cross compiler, fixed (I think) by installing lib32z1

`Src/Wlan` is still missing, but the make proceeds further.  The compilation output is a mess, there are plenty of not-found and similar errors throughout.  The make ends with `make: *** [Makefile:310: library] Error 2` and there is no `build` directory in `ports/w60x` (or anywhere else except `mpy-cross/build`).  So not there yet.  Any further ideas?

**Comment by robert-hh** [comment]
There is a src/Wlan directory in my tree, but it is empty. So you could try to just create it.
Src/Wlan is not included in the git repo list of files. That's why you did not get it. Looking at the places subdir.mk, where it is referenced, it seems to be excluded.
You can as well remove or comment lines 25-32 from subdir.mk, where the references to Src/Wlan happen. Both variant allow to build the firmware.
Edti: I'm running debian64 bit. No need for a lib32z1 lib..

**Comment by LexxM3** [comment]
Playing with Wlan cleaned up that error, but I am still not getting build and can see make errors.  Ok, I think I need to document every step from scratch and we'll see where we diverge.  Will document and update this with list of steps and results ...

Update: Ok, here is a full clean build attempt, same results as before (ignoring the missing Wlan red herring):

- clean minimal Debian install as follows (from `hostnamectl`):
   ```
    Operating System: Debian GNU/Linux 11 (bullseye)
    Kernel: Linux 5.10.0-19-amd64
    Architecture: x86-64
   ```
- `sudo apt update/full-upgrade` as of 17-Dec-2022 16:00EST

- `git clone git@github.com:robert-hh/micropython.git`
  - `git branch`; result: "* master"
  - `git checkout w60x`; result: "Switched to a new branch 'w60x'"
  - `git branch`; result: "* w60x"

- `git clone git@github.com:robert-hh/WM_SDK_W60X.git`
  - `git branch`; result: "* master"
  - `cd Src; mkdir Wlan`
  
- download crosscompiler `gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2`; exact path:
   ```
   https://launchpad.net/gcc-arm-embedded/4.9/4.9-2014-q4-major/+download/gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2
   ```

- `sudo mkdir /opt/tools`
- `cd /opt/tools`
- `sudo tar xf ~/downloads/gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2`
  - result: /opt/tools/gcc-arm-none-eabi-4_9-2014q4
- `sudo ln -s /opt/tools/gcc-arm-none-eabi-4_9-2014q4/ /opt/tools/arm-none-eabi-gcc`
  - result: /opt/tools/arm-none-eabi-gcc
  
- setup environment variables in .profile:
  - `export PATH=$PATH:/opt/tools/arm-none-eabi-gcc/bin`
  - `export WMSDK_PATH=/home/lexx/work/WM_SDK_W60X`
  - log out and log back in
  - check: `env | grep PATH`; result:
   ```
      WMSDK_PATH=/home/lexx/work/WM_SDK_W60X
      PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/tools/arm-none-eabi-gcc/bin
   ```  
  - check: `which arm-none-eabi-gcc`; result: "/opt/tools/arm-none-eabi-gcc/bin/arm-none-eabi-gcc"
  
  - try running: `arm-none-eabi-gcc`; result (this is the 64bit vs 32bit issue):
   ```
      -bash: /opt/tools/arm-none-eabi-gcc/bin/arm-none-eabi-gcc: No such file or directory
   ```
  - `sudo apt install lib32z1`
  - try running again: `arm-none-eabi-gcc`; result (seems fixed):
   ```
      arm-none-eabi-gcc: fatal error: no input files
      compilation terminated.
   ```
  - check version: `arm-none-eabi-gcc --version`; result (looks good):
   ```
      arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20141119 (release) [ARM/embedded-4_9-branch revision 218278]
      Copyright (C) 2014 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
   ```
- try to make mpy-cross:
  - `cd ~/work/micropython/mpy-cross`
  - `make`; result (looks good):
   ```
      LINK build/mpy-cross
         text    data     bss     dec     hex filename
       305602   13760     856  320218   4e2da build/mpy-cross
   ```
- try to make w60x:
  - `cd ~/work/micropython/ports/w60x/`
  - `make V=s`
  - output:
    - whole lot of stuff, but ...
    
    - head:
      ```
        COMPILER_OS: GNU/Linux
        Makefile:333: warning: overriding recipe for target 'clean'
        ../../py/mkrules.mk:242: warning: ignoring old recipe for target 'clean'
        make[1]: Entering directory '/home/lexx/work/WM_SDK_W60X/Src/App/mDNS'
      ```

    - tail:
      ```
        arm-none-eabi-ar ru /home/lexx/work/WM_SDK_W60X/Lib/GNU/wmota.a wm_http_fwup.o wm_socket_fwup.o
        make[1]: Leaving directory '/home/lexx/work/WM_SDK_W60X/Src/App/OTA'
        make[1]: Entering directory '/home/lexx/work/WM_SDK_W60X/Src/App/lwm2m-wakaama'
        make[1]: *** No targets specified and no makefile found.  Stop.
        make[1]: Leaving directory '/home/lexx/work/WM_SDK_W60X/Src/App/lwm2m-wakaama'
        make: *** [Makefile:310: library] Error 2
      ```
- some new .o files, no build

**Comment by LexxM3** [comment]
I am starting to get the hang of this Winner Micro "software support philosophy" in this WM_SDK.  Rule 1: if something doesn't work, delete it -- it probably shouldn't have been there IN A PUBLIC RELEASE TO THE WORLD in the first place. SMH.  `Src/Wlan` was one.  Seems like `Src/App/lwm2m-wakaama` is another ... so deleted that entire directory and removed references to it in various WM_SDK_W60X .def and .mk files.  Ran make again and made it MUCH MUCH further.  So now ...

Got
```
-e Error: micropython-lib submodule is not initialized. Run 'make submodules'
make: *** [../../py/mkrules.mk:188: build/frozen_content.c] Error 1
```
Easy, just ran `make submodules` and made it much further still.  So now ...

Got
```
freeze error executing "manifest.py": Error in manifest file: /home/lexx/work/micropython/ports/w60x/manifest.py: cannot stat /home/lexx/work/pye/pye.py
make: *** [../../py/mkrules.mk:189: build/frozen_content.c] Error 1
```
I guess I need `pye` repo.  Since we're not currently running it from `_boot.py`, I'll just comment it out from `manifest.py`.  While I am there, I guess I should also comment out `upysh`.   Ran make again and ...

Seem to have a completed build and image files in the build directory! Resultant wm_w600.fls works!  Woohoo!

**Comment by LexxM3** [comment]
A bit of funny problem, however:  the wm_w600.fls image I get is `MicroPython v1.15-2230-ge308f9700-dirty on 2022-12-17; WinnerMicro module with W600` -- v1.15!!??

Update: This is somehow related to github tags.  I compiled the `ports/unix` version both on this ([robert-hh](https://github.com/robert-hh) / [micropython](https://github.com/robert-hh/micropython)) fully sync'd master branch and also on the original ([micropython](https://github.com/micropython) / [micropython](https://github.com/micropython/micropython)) master branch.  The resulting binaries are identical size, but the former shows `MicroPython v1.15-2228-gbb77c1d5a on 2022-12-18; linux [GCC 10.2.1] version` and the latter shows the expected `MicroPython v1.19.1-776-gbb77c1d5a on 2022-12-18; linux [GCC 10.2.1] version`.  Also, the commit numbers `gbb77c1d5a` are the same, further supporting identical sources. And this is further supported by the fact that `sys.implementation` returns `version=(1, 19, 1)` for both of the `ports/unix` as well as my build of the running `ports/w60x`.

The header issue is correlated with the head tag of v1.15 on the former fork and the head tag of v1.19.1 of the latter root repo.  In other words, the image headers are generated from github tags and your fork doesn't include all the tags of the upstream root repo.

**Comment by robert-hh** [comment]
Mmh. If I build locally, I have v1.19.1-776. And git tag returns all tags up to v1.19.1. So I pushed the tags now.
About the previous posts: When you use Thonny, you do not need pye or upysh. upysh is in the micropython directory path.
References to Src/App/lwm2m-wakaama exists here and a Lib is built.
I added a dummy.txt file to Src/Wlan, such that the path exists now in the SDK.

**Comment by LexxM3** [comment]
> Mmh. If I build locally, I have v1.19.1-776. And git tag returns all tags up to v1.19.1. So I pushed the tags now.

I ran `git remote update` and it grabbed your pushed tags.  And yes, that works correctly now :-).  My new compiled image tag is `MicroPython v1.19.1-778-ge308f9700-dirty on 2022-12-18; WinnerMicro module with W600`

> About the previous posts: When you use Thonny, you do not need pye or upysh. upysh is in the micropython directory path.

This isn't a huge issue and I'll take a look at pye and upysh again at some point as those are definitely nice when Thonny or equivalent are not around.  But, just for precision, `manifest.py` points to both pye and upysh outside the repo directory path (i.e. as discrete components).

> References to Src/App/lwm2m-wakaama exists here and a Lib is built.

I am not sure what you mean?

I think my the issue is that there is no expected Makefile in the repo at `WM_SDK_W60X/Src/App/lwm2m-wakaama/`

> I added a dummy.txt file to Src/Wlan, such that the path exists now in the SDK.

I don't think you committed that yet, but no problem.

Any thoughts on the 64bit host OS vs 32bit ARM cross compiler issue above?

**Comment by robert-hh** [comment]
I did not commit that yet. Will do later. And change the upysh path 7. to point into the MP tree.

**Comment by LexxM3** [comment]
> I did not commit that yet. Will do later. And change the upysh path 7. to point into the MP tree.

I think upysh is actually in micropython-lib repo, not micropython.

**Comment by robert-hh** [comment]
It is, but as well linked into micropython/lib.

**Comment by LexxM3** [comment]
> It is, but as well linked into micropython/lib.

Ah, that's pretty sneaky.  Yes, it's there.  But the effect is that Github's Go To File feature doesn't find it, so it becomes a bit of "tribal knowledge" to know that :-).

**Comment by robert-hh** [comment]
So the WM_SDK_W60X repository is updated now, and I amended a change to the last w60x commit for micropython, to use the micropython/lib path for upysh and not to freeze pye by default. If there is a link to pye in the scripts directory, it will be included in your build.

**Comment by LexxM3** [comment]
Well I've figured out why `Src/App/lwm2m-wakaama` wasn't working.  The github repo of the SDK is missing the Makefile that is present in Winner Micro's G3.04 SDK zipfile distribution!!!  I've uploaded that Makefile to `Src/App/lwm2m-wakaama` and now make runs fine.  The Makefile in question attached (had to attach with .txt extension because Github wouldn't allow attachment otherwise, grr; remove .txt, of course).
[Makefile.txt](https://github.com/robert-hh/micropython/files/10255307/Makefile.txt)

Update: and the reason the Makefile was missing is because `Src/App/lwm2m-wakaama` is the only directory with a .gitignore and that .gitignore excluded a whole lot of stuff it both should and shouldn't, including Makefiles.  And incidentally, that .gitignore file (and a superfluous .gitmodules file) ARE in the original Winner Micro G3.04 zipfile distribution.  SMH again.

I am cleaning up and retesting the entire WM_SDK_W60X repo and will issue you a PR when ready.

**Comment by LexxM3** [comment]
> So the WM_SDK_W60X repository is updated now, and I amended a change to the last w60x commit for micropython, to use the micropython/lib path for upysh and not to freeze pye by default. If there is a link to pye in the scripts directory, it will be included in your build.

Thanks.  Just to note, that commit had WAY WAY WAY more than just Src/Wlan/* updates!  Still seems to compile ok.

**Comment by robert-hh** [comment]
I just looekd into it and found the same trouble about the .gitignore file. I cannot remember how I initially have set-up the SDK files to get them work.

> Thanks. Just to note, that commit had WAY WAY WAY more than just Src/Wlan/* updates! Still seems to compile ok.

Lots of .a files i assume, which are anyhow rebuilt. I should run `make clean` befire pushing the SDK.
