### ISSUE TITLE
AttributeError: 'module' object has no attribute 'RTC'

### ISSUE THREAD

**Issue by jkorte-dev** [robert-hh/micropython#21]
Hello Robert,

thanks for this great work to keep this port alive. 
Please apologize that I open a bug report. I am not sure if this is the right place to ask questions.

I flashed your latest firmware build (MicroPython v1.22.0-23.g99bb8cdd2 on 2023-12-27; Wemos W600 Pico with W600-B8) and it worked like a charm. But on boot a get a strange message:

WARNING: Could not sync device's clock: can't import name RTC

I tried different things
ntptime.settime()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ntptime.py", line 1, in settime
AttributeError: 'module' object has no attribute 'RTC'

from machine import RTC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: can't import name RTC

It seems that RTC is missing. 

Thank you very much

Jörg

**Comment by robert-hh** [comment]
Thanks for the hint. And yes, machine.RTC got lost in a previous code re-organisation, following the structure of the main line code. It's back again in the firmware images present on github and in the source code branch.
